// These items have special conversion amounts
export const ABOMINABLE_SALT = 476;
export const AEOLIAN_SCREAM = 773;
export const AMANITA_SHERRY = 928;
export const AN_IDENTITY_UNCOVERED = 657;
export const ANTIQUE_CONSTABLES_BADGE = 748;
export const APPALLING_SECRET = 390;
export const BROKEN_GIANT_1844 = 823;
export const BRIGHT_BRASS_SKULL = 749;
export const BRILLIANT_SOUL = 668;
export const COLLATED_RESEARCH = 745;
export const CORRESPONDENCE_PLAQUE = 932;
export const COMPROMISING_DOCUMENT = 830;
export const COPPER_CIPHER_RING = 758;
export const CRYPTIC_CLUE = 389;
export const DEAL_WITH_A_DEVIL = 984;
export const DIARY_OF_THE_DEAD = 762;
export const ENDOWMENT_OF_A_UNIVERSITY_FELLOWSHIP = 759;
export const ENGRAVED_PEWTER_TANKARD = 757;
export const ENTRY_IN_SLOWCAKES_EXCEPTIONALS = 752;
export const EXTRAORDINARY_IMPLICATION = 809;
export const FOXFIRE_CANDLE = 374;
export const GLIMPSE_OF_SOMETHING_LARGER = 983;
export const GREYFIELDS_1882 = 383;
export const INCENDIARY_GOSSIP = 659;
export const INKLING_OF_IDENTITY = 656;
export const INTRIGUING_SNIPPET = 588;
export const JADE_FRAGMENT = 377;
export const JOURNAL_OF_INFAMY = 525;
export const LAMPLIGHTER_BEESWAX = 384;
export const LAST_HOPE_OF_A_FIDGETING_WRITER = 986;
export const LENS_OF_BLACK_GLASS = 987;
export const MANIACS_PRAYER = 935;
export const MAP_SCRAP = 920;
export const MEMORY_OF_DISTANT_SHORES = 825;
export const MEMORY_OF_LIGHT = 589;
export const MORELWAYS_1872 = 815;
export const MOURNING_CANDLE = 951;
export const MUSCARIA_BRANDY = 927;
export const MYSTERY_OF_THE_ELDER_CONTINENT = 587;
export const NODULE_OF_PULSATING_AMBER = 754;
export const O_BOYLES_PRACTICAL_PRIMER = 756;
export const OLD_BONE_SKELETON_KEY = 753;
export const ORNATE_TYPEWRITER = 755;
export const PARTIAL_MAP = 956;
export const PHOSPHORESCENT_SCARAB = 652;
export const PRESBYTERATE_PASSPHRASE = 852;
export const PRIMORDIAL_SHRIEK = 388;
export const PRISONERS_HONEY = 391;
export const PROSCRIBED_MATERIAL = 420;
export const RED_FEATHERED_PIN = 761;
export const RELIC_OF_THE_THIRD_CITY = 424;
export const ROMANTIC_NOTION = 531;
export const ROOKERY_PASSWORD = 751;
export const ROOM_NUMBER_AT_THE_ROYAL_BETH = 985;
export const SENSE_OF_DEJA_VU = 982;
export const SHARD_OF_GLIM = 378;
export const SILK_SCRAP = 381;
export const SOUL = 386;
export const STOLEN_CORRESPONDENCE = 422;
export const STOLEN_KISS = 944;
export const STRANGLING_WILLOW_ABSINTHE = 822;
export const TALE_OF_TERROR = 828;
export const THIRSTY_BOMBAZINE_SCRAP = 922;
export const TINY_JEWELLED_RELIQUARY = 750;
export const TOUCHING_LOVE_STORY = 945;
export const SURFACE_SILK_SCRAP = 907;
export const VISION_OF_THE_SURFACE = 827;
export const WHISPER_SATIN_SCRAP = 915;
export const WHISPERED_HINT = 380;
export const ZEE_ZTORY = 831;

export const tier1 = [
  FOXFIRE_CANDLE,
  SOUL,
  WHISPERED_HINT,
  CRYPTIC_CLUE,
  STOLEN_CORRESPONDENCE,
  LAMPLIGHTER_BEESWAX,
  SHARD_OF_GLIM,
  GREYFIELDS_1882,
  SILK_SCRAP,
  PRIMORDIAL_SHRIEK,
  PRISONERS_HONEY,
  JADE_FRAGMENT,
  PROSCRIBED_MATERIAL,
];

export const tier2 = [
  ABOMINABLE_SALT,
  AMANITA_SHERRY,
  APPALLING_SECRET,
  INTRIGUING_SNIPPET,
  PHOSPHORESCENT_SCARAB,
  MAP_SCRAP,
  MORELWAYS_1872,
  SURFACE_SILK_SCRAP,
  MANIACS_PRAYER,
  ROMANTIC_NOTION,
  RELIC_OF_THE_THIRD_CITY,
  INKLING_OF_IDENTITY,
];

export const tier3 = [
  MEMORY_OF_DISTANT_SHORES,
  BRILLIANT_SOUL,
  TALE_OF_TERROR,
  COMPROMISING_DOCUMENT,
  MEMORY_OF_LIGHT,
  ZEE_ZTORY,
  STRANGLING_WILLOW_ABSINTHE,
  WHISPER_SATIN_SCRAP,
  JOURNAL_OF_INFAMY,
  CORRESPONDENCE_PLAQUE,
  VISION_OF_THE_SURFACE,
  MYSTERY_OF_THE_ELDER_CONTINENT,
  INCENDIARY_GOSSIP,
];

export const tier4 = [
  COLLATED_RESEARCH,
  MUSCARIA_BRANDY,
  EXTRAORDINARY_IMPLICATION,
  STOLEN_KISS,
  MOURNING_CANDLE,
  PARTIAL_MAP,
  BROKEN_GIANT_1844,
  THIRSTY_BOMBAZINE_SCRAP,
  AEOLIAN_SCREAM,
  TOUCHING_LOVE_STORY,
  PRESBYTERATE_PASSPHRASE,
  AN_IDENTITY_UNCOVERED,
];

// Faction items
export const factionItems = [
  OLD_BONE_SKELETON_KEY, // Criminals
  ENGRAVED_PEWTER_TANKARD, // Docks
  DIARY_OF_THE_DEAD, // Tomb-Colonies
  NODULE_OF_PULSATING_AMBER, // Rubberies
  ROOKERY_PASSWORD, // Urchins
  BRIGHT_BRASS_SKULL, // Hell
  ANTIQUE_CONSTABLES_BADGE, // Constables
  COPPER_CIPHER_RING, // Great Game
  TINY_JEWELLED_RELIQUARY, // Church
  ORNATE_TYPEWRITER, // Bohemians
  RED_FEATHERED_PIN, // Revolutionaries
  ENTRY_IN_SLOWCAKES_EXCEPTIONALS, // Society
  // ENDOWMENT_OF_A_UNIVERSITY_FELLOWSHIP, // University
  // O_BOYLES_PRACTICAL_PRIMER, // Widow
];

// Fidgeting Writer
export const fidgetingWriter = [
  TALE_OF_TERROR,
  SENSE_OF_DEJA_VU,
  GLIMPSE_OF_SOMETHING_LARGER,
  DEAL_WITH_A_DEVIL,
  ROOM_NUMBER_AT_THE_ROYAL_BETH,
  LAST_HOPE_OF_A_FIDGETING_WRITER,
  LENS_OF_BLACK_GLASS,
];

