import {
  OLD_BONE_SKELETON_KEY,
  ENGRAVED_PEWTER_TANKARD,
  DIARY_OF_THE_DEAD,
  NODULE_OF_PULSATING_AMBER,
  ROOKERY_PASSWORD,
  BRIGHT_BRASS_SKULL,
  ANTIQUE_CONSTABLES_BADGE,
  COPPER_CIPHER_RING,
  TINY_JEWELLED_RELIQUARY,
  ORNATE_TYPEWRITER,
  RED_FEATHERED_PIN,
  ENTRY_IN_SLOWCAKES_EXCEPTIONALS,
} from '../items/constants';

import {
  BOHEMIANS,
  CHURCH,
  CONSTABLES,
  CRIMINALS,
  DOCKS,
  GREAT_GAME,
  HELL,
  REVOLUTIONARIES,
  RUBBERIES,
  SOCIETY,
  TOMB_COLONIES,
  URCHINS,
} from './names';

// Map each item's ID to its corresponding faction
export const items = {
  [OLD_BONE_SKELETON_KEY]: CRIMINALS,
  [ENGRAVED_PEWTER_TANKARD]: DOCKS,
  [DIARY_OF_THE_DEAD]: TOMB_COLONIES,
  [NODULE_OF_PULSATING_AMBER]: RUBBERIES,
  [ROOKERY_PASSWORD]: URCHINS,
  [BRIGHT_BRASS_SKULL]: HELL,
  [ANTIQUE_CONSTABLES_BADGE]: CONSTABLES,
  [COPPER_CIPHER_RING]: GREAT_GAME,
  [TINY_JEWELLED_RELIQUARY]: CHURCH,
  [ORNATE_TYPEWRITER]: BOHEMIANS,
  [RED_FEATHERED_PIN]: REVOLUTIONARIES,
  [ENTRY_IN_SLOWCAKES_EXCEPTIONALS]: SOCIETY,
};

export function getFaction(itemID) {
  return items[itemID];
}
